
server:
  port: 8089
resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        wait-duration:
          seconds: 1
        retryExceptions:
          - java.lang.RuntimeException
    instances:
      exponential-backoff:
        max-attempts: 5
        wait-duration:
          seconds: 1
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
      random-backoff:
        max-attempts: 3
        wait-duration:
          seconds: 2s
        enable-randomized-wait: true
        randomized-wait-factor: 0.5
      service:
        base-config: default
      service-predicate:
        max-attempts: 3
        wait-duration:
          seconds: 2
        result-predicate: com.schooldevops.springjava.resilience4jtutorials.predicate.CommandPredicate
  circuitbreaker:
    configs:
      shared:
#        어떤 컴포넌트가 건강한지를 나타내는 헬스 인디케이터를 등록할지 여부를 설정한다. (이를 통해 서킷을 오픈할지 여부를 결정하기 위한 수단이다.)
        register-health-indicator: true
#        Circuit Breaker 를 기동할 기준 슬라이딩 윈도우 타입을 지정한다. (카운트 베이스, 타임 베이스) 가 있다.
        sliding-window-type: count_based
#        슬라이딩 윈도우 크기를 지정한다. count_base 을 진행할 시간을 나타낸다. 5초내
        sliding-window-size: 5
#        서킷이 오픈할 실패율을 지정한다. 여기서는 40%로 지정했다.
        failure-rate-threshold: 40
#        느린 호출 비율을 지정한다. 여기서는 40%로 지정했다.
        slow-call-rate-threshold: 40
#        하프오픈 상태에서 호출을 통과시킬 수를 지정한다.
        permitted-number-of-calls-in-half-open-state: 1
#        하프오픈 상태를 유지할 시간을 지정한다. 오픈되었다가 10초후 하프오픈이 된다.
        max-wait-duration-in-half-open-state:
          seconds: 10
#        느린 호출이라고 판단할 시간을 지정한다. 여기서는 2초 딜레이가 생기면 느린 호출이다.
        slow-call-duration-threshold:
          seconds: 2
#        예외 스택 트레이스를 수정할 수 있는지 여부를 지정한다. true는 Exception에 발생한 스택 트레이스를 수정할 수 있다.
        writable-stack-trace-enabled: true
#        서킷이 오픈되고 자동으로 하프오픈으로 전이할지 여부를 지정한다. true이면 자동으로 전이된다.
        automatic-transition-from-open-to-half-open-enabled: true

    instances:
      example-circuit:
        base-config: shared
management:
  endpoints:
    web:
      exposure:
        include: '*'
